<?php

namespace Time\TBSBundle\Repository;

/**
 * TbsManagersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TbsManagersRepository extends \Doctrine\ORM\EntityRepository
{
}
