<?php

namespace Time\TBSBundle\Repository;

/**
 * Tbs_PoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TbsPoleRepository extends \Doctrine\ORM\EntityRepository
{
}
